import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import './globals.css'
import { Theme } from '@radix-ui/themes'
import { Cormorant } from 'next/font/google'
import Image from 'next/image'

const cormorant = Cormorant({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cormorant',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cormorant.variable}>
      <body>
        <Theme
          accentColor="blue"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="full"
          appearance="light"
        >
          <Image
            src="/background.svg"
            alt="page_background"
            width="1530"
            height="994"
            style={{
              position: 'absolute',
              top: 0,
              left: -5,
              margin: '-10px',
              padding: '-20px',
            }}
          ></Image>
          {children}
        </Theme>
      </body>
    </html>
  )
}
